WebServer:
  Address: 0.0.0.0
  Port: 8000

Redis:
  Db: 0
  Address: '127.0.0.1:6379'
  Password: ''

Database:
  Host: '127.0.0.1'
  Port: 5432
  User: 'dev'
  Password: 'password'
  Database: 'dev'
  Prefix: 'oj_'
  MaxOpenConns: 100
  MaxIdleConns: 60
  ConnMaxLifetime: 60

Metrics:
  Namespace: 'OJ'
  Subsystem: 'server'

Development: true
