name: Docker Image

on:
  push:
    branches: [ "master", "develop" ]
    tags: [ "v*" ]
  pull_request:
    branches: [ "master", "develop" ]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Server Meta
        id: server_meta
        uses: docker/metadata-action@v4
        with:
          images: panpaul/woj-server
      - name: Build and Push the Server Image
        uses: docker/build-push-action@v3
        with:
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.server_meta.outputs.tags }}
          file: ./Dockerfile.server
          labels: ${{ steps.server_meta.outputs.labels }}
